FROM golang:1.10.0-alpine

# add git
RUN apk update && apk add git

# Installing Go dependencies
RUN go get github.com/Masterminds/glide

ENV SRC_DIR=/go/src/github.com/ilovelili/micro-k8s
WORKDIR $SRC_DIR

# Copying files
COPY . $SRC_DIR

# Running glide
RUN glide up

RUN go build

# ENTRYPOINT [ "./micro-k8s" ]

